version: 2

models:

  - name: model_dwd_order_transactions_view
    description: Order detail
    columns:
      - name: order_id
        description: >
          The primary key for this table
        datatype: varchar
        tests:
          - not_null
          - unique

      - name: customer_id
        description: >
          Customer ID ; Reference to model_dim_customer_profile_view
        datatype: varchar
        tests:
          - relationships:
              to: ref('model_dim_customers_profile_view')
              field: customer_id

      - name: restaurant_id
        description: >
          Restaurant ID ; Reference to model_dim_restaurant_profile_view
        datatype: varchar
        tests:
          - relationships:
              to: ref('model_dim_restaurant_profile_view')
              field: restaurant_id

      - name: driver_id
        description: Driver ID ; Reference to model_dim_driver_profile_view
        datatype: varchar
        tests:
          - relationships:
              to: ref('model_dim_driver_profile_view')
              field: driver_id

      - name: campaign_id
        description: Campaign ID ; Reference to model_dim_campaign_profile_view
        datatype: varchar
        tests:
          - relationships:
              to: ref('model_dim_campaign_profile_view')
              field: campaign_id

      - name: order_date
        description: Order Create Date
        datatype: date

      - name: order_datetime
        description: Order Create Datetime
        datatype: timestamp

      - name: pickup_datetime
        description: Pickup Create Datetime
        datatype: timestamp

      - name: delivery_datetime
        description: Delivery Create Datetime
        datatype: timestamp

      - name: is_net_order
        description: Flag whether is net order (order_status = 'completed')
        datatype: boolean
        tests:
          - not_null

      - name: delivery_zone
        description: Delivery Zone
        datatype: varchar

      - name: total_amount_thb
        description: Total order amount in Thai Baht
        datatype: double

      - name: is_late_delivery
        description: Flag whether order is late delivery
        datatype: boolean
        tests:
          - not_null

      - name: delivery_distance_km
        description: Delivery distance in kilometer
        datatype: double

  - name: model_dwd_order_delivery_view
    description: Order Delivery detail
    columns:
      - name: order_id
        description: The primary key for this table
        datatype: varchar
        tests:
          - relationships:
              to: ref('model_dwd_order_transactions_view')
              field: order_id

      - name: order_status
        description: Order Status
        datatype: varchar

      - name: order_create_datetime
        description: Order create datetime
        datatype: timestamp

      - name: order_accepted_datetime
        description: Order accepted datetime
        datatype: timestamp

      - name: order_picked_up_datetime
        description: Order picked up datetime
        datatype: timestamp

      - name: order_completed_datetime
        description: Order completed datetime
        datatype: timestamp

      - name: order_failed_datetime
        description: Order failed datetime
        datatype: timestamp

      - name: order_canceled_datetime
        description: Order canceled datetime
        datatype: timestamp
