version: 2

models:
  - name: model_dws_driver_delivery_heatmap
    description: >
      This model generates a heatmap of driver delivery activity, providing insights into delivery density 
      and patterns across different regions and time periods.
    columns:
      - name: driver_id
        description: >
          Unique identifier for the driver.
        data_type: varchar
      - name: delivery_date
        description: >
          The date of the delivery activity.
        data_type: date
      - name: region
        description: >
          The region where the delivery activity occurred.
        data_type: varchar
      - name: delivery_count
        description: >
          The total number of deliveries completed by the driver in the specified region and date.
        data_type: integer

  - name: model_dws_driver_profile
    description: >
      This model provides a detailed profile of drivers, including metrics such as delivery performance, 
      ratings, and activity status.
    columns:
      - name: driver_id
        description: >
          Unique identifier for the driver.
        data_type: varchar
      - name: total_deliveries
        description: >
          The total number of deliveries completed by the driver.
        data_type: integer
      - name: average_rating
        description: >
          The average rating of the driver based on customer feedback.
        data_type: double
      - name: is_active
        description: >
          Indicates whether the driver is currently active (1 for active, 0 for inactive).
        data_type: integer
      - name: region
        description: >
          The primary region where the driver operates.
        data_type: varchar