version: 2

models:
  - name: model_dws_campaign_performance_da
    description: >
      This model provides daily aggregated performance metrics for marketing campaigns, including impressions, clicks, 
      conversions, and revenue.
    columns:
      - name: campaign_id
        description: >
          Unique identifier for the campaign.
        data_type: varchar
      - name: report_date
        description: >
          The date for which the performance metrics are reported.
        data_type: date
      - name: impressions
        description: >
          The total number of impressions for the campaign on the given date.
        data_type: integer
      - name: clicks
        description: >
          The total number of clicks for the campaign on the given date.
        data_type: integer
      - name: conversions
        description: >
          The total number of conversions for the campaign on the given date.
        data_type: integer
      - name: revenue_thb
        description: >
          The total revenue generated by the campaign on the given date, in Thai Baht (THB).
        data_type: double

  - name: model_dws_campaign_profile
    description: >
      This model provides detailed information about marketing campaigns, including their objectives, budgets, 
      and targeting strategies.
    columns:
      - name: campaign_id
        description: >
          Unique identifier for the campaign.
        data_type: varchar
      - name: campaign_name
        description: >
          The name of the campaign.
        data_type: varchar
      - name: start_date
        description: >
          The start date of the campaign.
        data_type: date
      - name: end_date
        description: >
          The end date of the campaign.
        data_type: date
      - name: objective
        description: >
          The primary objective of the campaign (e.g., awareness, conversion).
        data_type: varchar
      - name: budget_thb
        description: >
          The total budget allocated for the campaign, in Thai Baht (THB).
        data_type: double

  - name: model_dws_customer_acquisition
    description: >
      This model tracks customer acquisition metrics, including the number of new customers acquired through campaigns.
    columns:
      - name: acquisition_date
        description: >
          The date when the customer was acquired.
        data_type: date
      - name: campaign_id
        description: >
          Unique identifier for the campaign responsible for the acquisition.
        data_type: varchar
      - name: new_customers
        description: >
          The total number of new customers acquired on the given date.
        data_type: integer

  - name: model_dws_customer_retarget
    description: >
      This model tracks retargeting metrics, including the number of returning customers engaged through campaigns.
    columns:
      - name: retarget_date
        description: >
          The date when the customer was retargeted.
        data_type: date
      - name: campaign_id
        description: >
          Unique identifier for the campaign responsible for the retargeting.
        data_type: varchar
      - name: returning_customers
        description: >
          The total number of returning customers engaged on the given date.
        data_type: integer

  - name: model_dws_customers_profile_da
    description: >
      This model provides daily aggregated profiles of customers, including their activity and engagement metrics.
    columns:
      - name: customer_id
        description: >
          Unique identifier for the customer.
        data_type: varchar
      - name: report_date
        description: >
          The date for which the customer profile metrics are reported.
        data_type: date
      - name: total_orders
        description: >
          The total number of orders placed by the customer on the given date.
        data_type: integer
      - name: total_spent_thb
        description: >
          The total amount spent by the customer on the given date, in Thai Baht (THB).
        data_type: double