version: 2

models:
  - name: model_dws_campaign_performance
    description: >
      This model provides daily aggregated performance metrics for marketing campaigns, including impressions, interactions, 
      conversions, customer acquisition, advertising costs, and revenue.
    columns:
      - name: report_date
        description: >
          The date for which the campaign performance metrics are reported.
        data_type: date
        tests:
          - not_null
      - name: campaign_id
        description: >
          Campaign ID.
        data_type: varchar
        tests:
          - not_null
          - unique
      - name: campaign_name
        description: >
          The name of the campaign.
        data_type: varchar
      - name: start_date
        description: >
          The start date of the campaign.
        data_type: date
      - name: end_date
        description: >
          The end date of the campaign.
        data_type: date
      - name: campaign_type
        description: >
          The type of campaign.
        data_type: varchar
      - name: objective
        description: >
          The primary objective of the campaign.
        data_type: varchar
      - name: channel
        description: >
          The channel through which the campaign was conducted.
        data_type: varchar
      - name: budget
        description: >
          The total budget allocated for the campaign.
        data_type: double
      - name: cost_model
        description: >
          The cost model used for the campaign.
        data_type: varchar
      - name: targeting_strategy
        description: >
          The strategy used for targeting customers in the campaign.
        data_type: varchar
      - name: cnt_exposure
        description: >
          The total number of exposures (impressions) for the campaign on the given date.
        data_type: integer
      - name: cnt_interaction
        description: >
          The total number of interactions (clicks) for the campaign on the given date.
        data_type: integer
      - name: cnt_customer_conversion_completed
        description: >
          The total number of customers who completed a conversion and whose orders are marked as net orders.
        data_type: integer
      - name: ad_cost_thb
        description: >
          The total advertising cost for the campaign on the given date, in Thai Baht (THB).
        data_type: double
      - name: revenue_thb
        description: >
          The total revenue generated from net orders for the campaign on the given date, in Thai Baht (THB).
        data_type: double

models:
  - name: model_dws_campaign_profile
    description: >
      This model provides detailed performance metrics for marketing campaigns, including exposure, interaction, 
      conversion counts, customer acquisition, advertising costs, and revenue.
    columns:
      - name: campaign_id
        description: >
          Unique identifier for the campaign.
        data_type: varchar
      - name: campaign_name
        description: >
          The name of the campaign.
        data_type: varchar
      - name: start_date
        description: >
          The start date of the campaign.
        data_type: date
      - name: end_date
        description: >
          The end date of the campaign.
        data_type: date
      - name: campaign_type
        description: >
          The type of campaign
        data_type: varchar
      - name: objective
        description: >
          The primary objective of the campaign
        data_type: varchar
      - name: channel
        description: >
          The channel through which the campaign was conducted.
        data_type: varchar
      - name: budget
        description: >
          The total budget allocated for the campaign.
        data_type: double
      - name: cost_model
        description: >
          The cost model used for the campaign.
        data_type: varchar
      - name: targeting_strategy
        description: >
          The strategy used for targeting customers in the campaign.
        data_type: varchar
      - name: cnt_exposure
        description: >
          The total number of exposures (impressions) for the campaign.
        data_type: integer
      - name: cnt_interaction
        description: >
          The total number of interactions (clicks) for the campaign.
        data_type: integer
      - name: cnt_conversion
        description: >
          The total number of conversions for the campaign.
        data_type: integer
      - name: cnt_customer_conversion_completed
        description: >
          The total number of customers who completed a conversion and whose orders are marked as net orders.
        data_type: integer
      - name: cnt_customer_acquistion_completed
        description: >
          The total number of new customers acquired through the campaign.
        data_type: integer
      - name: ad_cost_thb
        description: >
          The total advertising cost for the campaign, in Thai Baht (THB).
        data_type: double
      - name: ad_cost_acquistion_thb
        description: >
          The advertising cost specifically for acquiring new customers, in Thai Baht (THB).
        data_type: double
      - name: revenue_thb
        description: >
          The total revenue generated from net orders for the campaign, in Thai Baht (THB).
        data_type: double
      - name: cost_per_acquired_customer
        description: >
          The average cost of acquiring a new customer through the campaign, in Thai Baht (THB).
        data_type: double
      - name: return_on_ad_spend_thb
        description: >
          The return on ad spend (ROAS) for the campaign, calculated as revenue minus advertising costs, in Thai Baht (THB).
        data_type: double

models:
  - name: model_dws_customer_acquisition
    description: >
      This model tracks customer acquisition metrics, including the number of new customers acquired through campaigns, 
      their behavior, and campaign performance metrics such as average purchase value and retention duration.
    columns:
      - name: campaign_type
        description: >
          The type of campaign
        data_type: varchar
      - name: objective
        description: >
          The primary objective of the campaign
        data_type: varchar
      - name: channel
        description: >
          The channel through which the campaign was conducted
        data_type: varchar
      - name: platform
        description: >
          The platform used for the campaign
        data_type: varchar
      - name: campaign_id
        description: >
          Campaign ID
        data_type: varchar
      - name: cnt_first_time_campaign_customer
        description: >
          The total number of first-time customers acquired through the campaign.
        data_type: integer
      - name: avg_purchase_value_thb
        description: >
          The average purchase value of customers acquired through the campaign, in Thai Baht (THB).
        data_type: double
      - name: avg_repeated_order_after_acquistion
        description: >
          The average number of repeated orders placed by customers after acquisition.
        data_type: double
      - name: avg_customer_retention_day
        description: >
          The average duration, in days, that customers retained after their first transaction.
        data_type: double
      - name: avg_interaction_order_sec
        description: >
          The average time, in seconds, between the first interaction with the campaign and the first order.
        data_type: double
      - name: total_ad_cost_thb
        description: >
          The total advertising cost for the campaign, in Thai Baht (THB).
        data_type: double

models:
  - name: model_dws_customer_retarget
    description: >
      This model tracks retargeting campaign performance, including metrics such as the number of customers targeted, 
      return and retention ratios, total spending after retargeting, and the average time gap between the original 
      and return orders.
    columns:
      - name: campaign_id
        description: >
          Unique identifier for the retargeting campaign.
        data_type: varchar
      - name: targeting_strategy
        description: >
          The strategy used for targeting customers in the retargeting campaign.
        data_type: varchar
      - name: cnt_customers_targeted
        description: >
          The total number of unique customers targeted by the retargeting campaign.
        data_type: integer
      - name: ratio_returned_customer
        description: >
          The ratio of customers who returned after being targeted by the retargeting campaign.
        data_type: double
      - name: total_spend_after_retarget_thb
        description: >
          The total amount spent by customers after being targeted by the retargeting campaign, in Thai Baht (THB).
        data_type: double
      - name: avg_time_gap_original_return_order_day
        description: >
          The average time gap, in days, between the original order and the return order after retargeting.
        data_type: double
      - name: ratio_retained_customer
        description: >
          The ratio of customers who were retained (placed additional orders within 30 days) after being targeted by the retargeting campaign.
        data_type: double