version: 2

models:
  - name: model_dim_restaurant_profile_view
    description: >
      This model creates a view of restaurant profiles, including details such as name, category, location, 
      average rating, active status, and preparation time.
    columns:
      - name: restaurant_id
        description: >
          Unique identifier for the restaurant.
        data_type: varchar
        tests:
          - not_null
          - unique
      - name: restaurant_name
        description: >
          The name of the restaurant.
        data_type: varchar
      - name: category
        description: >
          The category or type of cuisine offered by the restaurant (e.g., fast food, fine dining).
        data_type: varchar
      - name: city
        description: >
          The city where the restaurant is located.
        data_type: varchar
      - name: average_rating
        description: >
          The average customer rating for the restaurant.
        data_type: double
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5
      - name: is_active
        description: >
          Indicates whether the restaurant is currently active (true for active, false for inactive).
        data_type: boolean
        tests:
          - not_null
      - name: prep_time_min
        description: >
          The average preparation time for orders at the restaurant, in minutes.
        data_type: integer