version: 2

models:
  - name: model_dim_customers_profile_view
    description: Customer Profile Data
    columns:
      - name: customer_id
        description: The primary key for this table
        datatype: varchar
        tests:
          - unique
          - not_null
      - name: signup_date
        description: The date the customer signed up
        datatype: date
      - name: referral_source
        description: Acquisition Source
        datatype: varchar
      - name: customer_segment
        description: Customer Segment
        datatype: varchar
      - name: is_active
        description: Flag whether customer active
        datatype: boolean
      - name: birth_year
        description: The year the customer was born
        datatype: int
      - name: gender
        description: Customer Gender [0 = Male, 1 = Female, 2 = Other]
        datatype: tinyint
      - name: preferred_device
        description: Customer preferred device
        datatype: varchar
  - name: model_dim_restaurants_profile_view
    description: Restaurants Profile Data
    columns:
      - name: restaurant_id
        description: The primary key for this table
        datatype: varchar
      - name: name
        description: Restaurant Name
        datatype: varchar
      - name: category
        description: Restaurant Category
        datatype: varchar
      - name: city
        description: City where restaurant located
        datatype: varchar
      - name: average_rating
        description: Restaurant average rating
        datatype: double
      - name: is_active
        description: Flag whether restaurant is active
        datatype: boolean
      - name: prep_time_min
        description: Restaurant preparation time in minute
        datatype: bigint
  - name: model_dim_campaign_profile_view
    description: Campaign Profile Data
    columns:
      - name: campaign_id
        description: The primary key for this table
        datatype: varchar
      - name: campaign_name
        description: Campaign Name
        datatype: varchar
      - name: start_date
        description: Campaign Start Date
        datatype: date
      - name: end_date
        description: Campaign End Date
        datatype: date
      - name: campaign_duration_day
        description: Campaign Duration in day
        datatype: bigint
      - name: campaign_type
        description: Campaign Type
        datatype: varchar
      - name: objective
        description: Campaign Objective
        datatype: varchar
      - name: channel
        description: Campaign Channel
        datatype: varchar
      - name: budget
        description: Campaign budget
        datatype: double
      - name: cost_model
        description: Cost Model
        datatype: varchar
      - name: targeting_strategy
        description: Campaign targeting stratefy
        datatype: varchar
      - name: is_active
        description: Flag whether campaign active
        datatype: boolean
  - name: model_dwd_order_transactions_view
    description: Order detail
    columns:
      - name: order_id
        description: The primary key for this table
        datatype: varchar
    columns:
      - name: customer_id
        description: Customer ID ; Reference to model_dim_customer_profile_view
        datatype: varchar
        tests:
          - relationships:
              to: ref('model_dim_customers_profile_view')
              field: customer_id
    columns:
      - name: restaurant_id
        description: Restaurant ID ; Reference to model_dim_restaurant_profile_view
        datatype: varchar
        tests:
          - relationships:
              to: ref('model_dim_restaurant_profile_view')
              field: restaurant_id
    columns:
      - name: driver_id
        description: Driver ID ; Reference to model_dim_driver_profile_view
        datatype: varchar
        tests:
          - relationships:
              to: ref('model_dim_driver_profile_view')
              field: driver_id
    columns:
      - name: campaign_id
        description: Campaign ID ; Reference to model_dim_campaign_profile_view
        datatype: varchar
        tests:
          - relationships:
              to: ref('model_dim_campaign_profile_view')
              field: campaign_id
    columns:
      - name: order_date
        description: Order Create Date
        datatype: date
    columns:
      - name: order_datetime
        description: Order Create Datetime
        datatype: timestamp
    columns:
      - name: pickup_datetime
        description: Pickup Create Datetime
        datatype: timestamp
    columns:
      - name: delivery_datetime
        description: Delivery Create Datetime
        datatype: timestamp
    columns:
      - name: order_status
        description: Order Status
        datatype: varchar
    columns:
      - name: is_net_order
        description: Flag whether is net order (order_status = 'completed')
        datatype: boolean
    columns:
      - name: delivery_zone
        description: Delivery Zone
        datatype: varchar
    columns:
      - name: total_amount_thb
        description: Total order amount in Thai Baht
        datatype: double
    columns:
      - name: is_late_delivery
        description: Flag whether order is late delivery
        datatype: boolean
    columns:
      - name: delivery_distance_km
        description: Delivery distance in kilometer
        datatype: double
  - name: model_dwd_order_delivery_view
    description: Order Delivery detail
    columns:
      - name: order_id
        description: The primary key for this table
        datatype: varchar
    columns:
      - name: order_status
        description: Order Status
        datatype: varchar
      - name: order_create_datetime
        description: Order create datetime
        datatype: timestamp
      - name: order_accepted_datetime
        description: Order accepted datetime
        datatype: timestamp
      - name: order_picked_up_datetime
        description: Order picked up datetime
        datatype: timestamp
      - name: order_completed_datetime
        description: Order completed datetime
        datatype: timestamp
      - name: order_failed_datetime
        description: Order failed datetime
        datatype: timestamp
      - name: order_canceled_datetime
        description: Order canceled datetime
        datatype: timestamp
  - name: model_dim_drivers_profile_view
    description: Driver profile detail
    columns:
      - name: driver_id
        description: The primary key for this table
        datatype: varchar
      - name: join_date
        description: Driver join date
        datatype: date
      - name: vehicle_type
        description: Driver vehicle type
        datatype: varchar
      - name: region
        description: Driver region
        datatype: varchar
      - name: is_active
        description: Flag whether driver is active
        datatype: boolean
      - name: driver_rating
        description: Driver rating
        datatype: double
      - name: bonus_tier
        description: Driver bonus tier
        datatype: double
  - name: model_dwd_campaign_interactions_view
    description: Campaign interaction detail
    columns:
      - name: interaction_id
        description: The primary key for this table
        datatype: varchar
      - name: campaign_id
        description: Campaign ID ; Reference to model_dim_campaign_profile_view
        datatype: varchar
        tests:
          - relationships:
              to: ref('model_dim_campaign_profile_view')
              field: campaign_id
      - name: customer_id
        description: Customer ID ; Reference to model_id_dim_customers_profile_view
        datatype: varchar
        tests:
          - relationships:
              to: ref('model_id_dim_customers_profile_view')
              field: customer_id
      - name: session_id
        description: Session ID ; Reference to model_id_dwd_customer_app_sessions_view
        datatype: varchar
        tests:
          - relationships:
              to: ref('model_id_dwd_customer_app_sessions_view')
              field: session_id
      - name: order_id
        description: Order ID ; Reference to model_dwd_order_transactions_view
        datatype: varchar
        tests:
          - relationships:
              to: ref('model_dwd_order_transactions_view')
              field: order_id
      - name: interaction_date
        description: User interaction date
        datatype: varchar
      - name: interaction_datetime
        description: User interaction datetime
        datatype: timestamp
      - name: event_type
        description: event_type
        datatype: varchar
      - name: platform
        description: Platfrom which releated to campaign
        datatype: varchar
      - name: device_type
        description: Device type which user is used
        datatype: varchar
      - name: ad_cost_thb
        description: advertisement cost for each interaction in Thai Baht
        datatype: double
      - name: revenue_thb
        description: Revenue from each order by these campaign in Thai Baht
        datatype: double
      - name: is_new_customer
        description: Flag whether new customer
        datatype: Boolean