version: 2

models:
  - name: model_dws_customers_profile_da
    description: Customer profile data
    columns:
      - name: customer_id
        description: The primary key for this table
        datatype: varchar
        tests:
          - unique
          - not_null
      # Basic Information
      - name: signup_date
        description: The date the customer signed up
        datatype: date
      - name: referral_source
        description: Acquisition Source
        datatype: varchar
      - name: customer_segment
        description: Customer Segment
        datatype: varchar
      - name: is_active
        description: Flag whether customer active
        datatype: tinyint
      - name: birth_year
        description: The year the customer was born
        datatype: int
      - name: gender
        description: Customer Gender [0 = Male, 1 = Female, 2 = Other]
        datatype: TINYINT
      - name: preferred_device
        description: Customer preferred device
        datatype: varchar
      # Active Date
      - name: first_active_date
        description: The date the customer first became active
        datatype: date
      - name: latest_active_date
        description: The date the customer was last active
        datatype: date
      # Customer Order
      - name: total_net_orders
        description: The total number of net orders placed by the customer
        datatype: int
      - name: total_gross_orders
        description: The total number of gross orders placed by the customer
        datatype: int
      - name: total_spent
        description: The total amount spent from net orders by the customer
        datatype: int
      - name: avg_order_value
        description: The average amount spent per order by the customer
        datatype: double
      - name: first_order_date
        description: The date of the customer's first order
        datatype: date
      - name: latest_order_date
        description: The date of the customer's last order
        datatype: date
      - name: most_frequent_restaurant
        description: The restaurant where the customer has placed the most orders
        datatype: varchar
      - name: total_order_from_restaurant
        description: The total number of orders placed by the customer from their most frequent restaurant
        datatype: int
      # Campaign Engagement
      - name: total_campaigns_engaged
        description: The total number of campaigns the customer has engaged with
        datatype: int
      - name: total_campaigns_clicked
        description: The total number of campaigns the customer has clicked on
        datatype: int
      - name: total_campaigns_converted
        description: The total number of campaigns the customer has converted from
        datatype: int
      - name: first_campaign_id_engagement
        description: The ID of the first campaign the customer engaged with
        datatype: varchar
      - name: first_campaign_date_engagement
        description: The date of the customer's first campaign engagement
        datatype: date
      - name: first_campaign_id_converted
        description: The ID of the first campaign the customer converted
        datatype: varchar
      - name: first_campaign_date_converted
        description: The date of the customer's first campaign conversion
        datatype: date
      - name: total_campaign_cost
        description: The total cost of campaigns the customer has engaged with
        datatype: double
      - name: total_campaign_revenue
        description: The total revenue generated from campaigns the customer has engaged with
        datatype: double